# Generated by Django 5.0.6 on 2024-05-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DICOMMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_id', models.CharField(max_length=20)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('study_id', models.CharField(max_length=50)),
                ('study_description', models.CharField(max_length=255)),
                ('study_date', models.DateField()),
                ('modality', models.CharField(max_length=10)),
                ('pixel_spacing', models.CharField(max_length=50)),
            ],
        ),
    ]
